export const HOME_URL = "/"
export const LOGIN_URL = "/login"
export const SIGNIN_URL = "/signin"
export const CATALOGO_URL = "/catalogo"
export const CHAT_URL = "/chat"
export const PACIENTE_URL = "/paciente/:id_paciente"
export const DOCTOR_URL = "/doctor/:id_doctor"
